#!/bin/sh
if head -1 "$1" | grep -qE "^(Merge|merge) .{1,}$"; then
    echo "$(head -1 "$1")" >&2
    exit 0
fi

if [ "$branch" != "master" ]; then
    if ! head -1 "$1" | grep -qE "^(ALT|ADD|FIX|DEL|GIT): (TR)-[0-9]{1,}. .{1,}$"; then
        echo "$(head -1 "$1")" >&2
        echo "Aborting commit. Your commit message is invalid." >&2
        echo "Format should be: <type>: <trellocode> <description>" >&2
        echo "<type> must be: ALT, ADD, FIX, DEL, GIT" >&2
        echo "Like: ALT: TR-999. MENSAGEM DO COMMIT" >&2
        exit 1
    fi
fi